	const_def 1
	const GRASS_ENERGY                ; $01
	const FIRE_ENERGY                 ; $02
	const WATER_ENERGY                ; $03
	const LIGHTNING_ENERGY            ; $04
	const PSYCHIC_ENERGY              ; $05
	const FIGHTING_ENERGY             ; $06
	const DARKNESS_ENERGY             ; $07
	const METAL_ENERGY                ; $08
	const DOUBLE_COLORLESS_ENERGY     ; $09
	const BULBASAUR                   ; $0a
	const IVYSAUR                     ; $0b
	const VENUSAUR_LV64               ; $0c
	const VENUSAUR_LV67               ; $0d
	const CATERPIE                    ; $0e
	const METAPOD                     ; $0f
	const BUTTERFREE                  ; $10
	const WEEDLE                      ; $11
	const KAKUNA                      ; $12
	const BEEDRILL                    ; $13
	const EKANS                       ; $14
	const ARBOK                       ; $15
	const NIDORANF                    ; $16
	const NIDORINA                    ; $17
	const NIDOQUEEN                   ; $18
	const NIDORANM                    ; $19
	const NIDORINO                    ; $1a
	const NIDOKING                    ; $1b
	const ZUBAT                       ; $1c
	const GOLBAT                      ; $1d
	const ODDISH                      ; $1e
	const GLOOM                       ; $1f
	const VILEPLUME                   ; $20
	const PARAS                       ; $21
	const PARASECT                    ; $22
	const VENONAT                     ; $23
	const VENOMOTH                    ; $24
	const BELLSPROUT                  ; $25
	const WEEPINBELL                  ; $26
	const VICTREEBEL                  ; $27
	const GRIMER                      ; $28
	const MUK                         ; $29
	const EXEGGCUTE                   ; $2a
	const EXEGGUTOR                   ; $2b
	const KOFFING                     ; $2c
	const WEEZING                     ; $2d
	const TANGELA_LV8                 ; $2e
	const TANGELA_LV12                ; $2f
	const SCYTHER                     ; $30
	const PINSIR                      ; $31
	const CHARMANDER                  ; $32
	const CHARMELEON                  ; $33
	const CHARIZARD                   ; $34
	const VULPIX                      ; $35
	const NINETALES_LV32              ; $36
	const NINETALES_LV35              ; $37
	const GROWLITHE                   ; $38
	const ARCANINE_LV34               ; $39
	const ARCANINE_LV45               ; $3a
	const PONYTA                      ; $3b
	const RAPIDASH                    ; $3c
	const MAGMAR_LV24                 ; $3d
	const MAGMAR_LV31                 ; $3e
	const FLAREON_LV22                ; $3f
	const FLAREON_LV28                ; $40
	const MOLTRES_LV35                ; $41
	const MOLTRES_LV37                ; $42
	const SQUIRTLE                    ; $43
	const WARTORTLE                   ; $44
	const BLASTOISE                   ; $45
	const PSYDUCK                     ; $46
	const GOLDUCK                     ; $47
	const POLIWAG                     ; $48
	const POLIWHIRL                   ; $49
	const POLIWRATH                   ; $4a
	const TENTACOOL                   ; $4b
	const TENTACRUEL                  ; $4c
	const SEEL                        ; $4d
	const DEWGONG                     ; $4e
	const SHELLDER                    ; $4f
	const CLOYSTER                    ; $50
	const KRABBY                      ; $51
	const KINGLER                     ; $52
	const HORSEA                      ; $53
	const SEADRA                      ; $54
	const GOLDEEN                     ; $55
	const SEAKING                     ; $56
	const STARYU                      ; $57
	const STARMIE                     ; $58
	const MAGIKARP                    ; $59
	const GYARADOS                    ; $5a
	const LAPRAS                      ; $5b
	const VAPOREON_LV29               ; $5c
	const VAPOREON_LV42               ; $5d
	const OMANYTE                     ; $5e
	const OMASTAR                     ; $5f
	const ARTICUNO_LV35               ; $60
	const ARTICUNO_LV37               ; $61
	const PIKACHU_LV12                ; $62
	const PIKACHU_LV14                ; $63
	const PIKACHU_LV16                ; $64
	const PIKACHU_ALT_LV16            ; $65
	const FLYING_PIKACHU              ; $66
	const SURFING_PIKACHU_LV13        ; $67
	const SURFING_PIKACHU_ALT_LV13    ; $68
	const RAICHU_LV40                 ; $69
	const RAICHU_LV45                 ; $6a
	const MAGNEMITE_LV13              ; $6b
	const MAGNEMITE_LV15              ; $6c
	const MAGNETON_LV28               ; $6d
	const MAGNETON_LV35               ; $6e
	const VOLTORB                     ; $6f
	const ELECTRODE_LV35              ; $70
	const ELECTRODE_LV42              ; $71
	const ELECTABUZZ_LV20             ; $72
	const ELECTABUZZ_LV35             ; $73
	const JOLTEON_LV24                ; $74
	const JOLTEON_LV29                ; $75
	const ZAPDOS_LV40                 ; $76
	const ZAPDOS_LV64                 ; $77
	const ZAPDOS_LV68                 ; $78
	const SANDSHREW                   ; $79
	const SANDSLASH                   ; $7a
	const DIGLETT                     ; $7b
	const DUGTRIO                     ; $7c
	const MANKEY                      ; $7d
	const PRIMEAPE                    ; $7e
	const MACHOP                      ; $7f
	const MACHOKE                     ; $80
	const MACHAMP                     ; $81
	const GEODUDE                     ; $82
	const GRAVELER                    ; $83
	const GOLEM                       ; $84
	const ONIX                        ; $85
	const CUBONE                      ; $86
	const MAROWAK_LV26                ; $87
	const MAROWAK_LV32                ; $88
	const HITMONLEE                   ; $89
	const HITMONCHAN                  ; $8a
	const RHYHORN                     ; $8b
	const RHYDON                      ; $8c
	const KABUTO                      ; $8d
	const KABUTOPS                    ; $8e
	const AERODACTYL                  ; $8f
	const ABRA                        ; $90
	const KADABRA                     ; $91
	const ALAKAZAM                    ; $92
	const SLOWPOKE_LV9                ; $93
	const SLOWPOKE_LV18               ; $94
	const SLOWBRO                     ; $95
	const GASTLY_LV8                  ; $96
	const GASTLY_LV17                 ; $97
	const HAUNTER_LV17                ; $98
	const HAUNTER_LV22                ; $99
	const GENGAR                      ; $9a
	const DROWZEE                     ; $9b
	const HYPNO                       ; $9c
	const MR_MIME                     ; $9d
	const JYNX                        ; $9e
	const MEWTWO_LV53                 ; $9f
	const MEWTWO_LV60                 ; $a0
	const MEWTWO_ALT_LV60             ; $a1
	const MEW_LV8                     ; $a2
	const MEW_LV15                    ; $a3
	const MEW_LV23                    ; $a4
	const PIDGEY                      ; $a5
	const PIDGEOTTO                   ; $a6
	const PIDGEOT_LV38                ; $a7
	const PIDGEOT_LV40                ; $a8
	const RATTATA                     ; $a9
	const RATICATE                    ; $aa
	const SPEAROW                     ; $ab
	const FEAROW                      ; $ac
	const CLEFAIRY                    ; $ad
	const CLEFABLE                    ; $ae
	const JIGGLYPUFF_LV12             ; $af
	const JIGGLYPUFF_LV13             ; $b0
	const JIGGLYPUFF_LV14             ; $b1
	const WIGGLYTUFF                  ; $b2
	const MEOWTH_LV14                 ; $b3
	const MEOWTH_LV15                 ; $b4
	const PERSIAN                     ; $b5
	const FARFETCHD                   ; $b6
	const DODUO                       ; $b7
	const DODRIO                      ; $b8
	const LICKITUNG                   ; $b9
	const CHANSEY                     ; $ba
	const KANGASKHAN                  ; $bb
	const TAUROS                      ; $bc
	const DITTO                       ; $bd
	const EEVEE                       ; $be
	const PORYGON                     ; $bf
	const SNORLAX                     ; $c0
	const DRATINI                     ; $c1
	const DRAGONAIR                   ; $c2
	const DRAGONITE_LV41              ; $c3
	const DRAGONITE_LV45              ; $c4
	const PROFESSOR_OAK               ; $c5
	const IMPOSTER_PROFESSOR_OAK      ; $c6
	const BILL                        ; $c7
	const MR_FUJI                     ; $c8
	const LASS                        ; $c9
	const IMAKUNI_CARD                ; $ca
	const POKEMON_TRADER              ; $cb
	const POKEMON_BREEDER             ; $cc
	const CLEFAIRY_DOLL               ; $cd
	const MYSTERIOUS_FOSSIL           ; $ce
	const ENERGY_RETRIEVAL            ; $cf
	const SUPER_ENERGY_RETRIEVAL      ; $d0
	const ENERGY_SEARCH               ; $d1
	const ENERGY_REMOVAL              ; $d2
	const SUPER_ENERGY_REMOVAL        ; $d3
	const SWITCH                      ; $d4
	const POKEMON_CENTER              ; $d5
	const POKE_BALL                   ; $d6
	const SCOOP_UP                    ; $d7
	const COMPUTER_SEARCH             ; $d8
	const POKEDEX                     ; $d9
	const PLUSPOWER                   ; $da
	const DEFENDER                    ; $db
	const ITEM_FINDER                 ; $dc
	const GUST_OF_WIND                ; $dd
	const DEVOLUTION_SPRAY            ; $de
	const POTION                      ; $df
	const SUPER_POTION                ; $e0
	const FULL_HEAL                   ; $e1
	const REVIVE                      ; $e2
	const MAINTENANCE                 ; $e3
	const POKEMON_FLUTE               ; $e4
	const GAMBLER                     ; $e5
	const RECYCLE                     ; $e6
DEF NUM_CARDS EQU const_value - 1
