; cgb palette size
DEF palettes EQUS "* PAL_SIZE"

DEF NUM_BACKGROUND_PALETTES EQU 8
DEF NUM_OBJECT_PALETTES     EQU 8

DEF PALRGB_WHITE EQU (COLOR_CH_MAX << B_COLOR_BLUE) | (COLOR_CH_MAX << B_COLOR_GREEN) | (COLOR_CH_MAX << B_COLOR_RED)

; tile size
DEF tiles EQUS "* TILE_SIZE"

DEF TILE_SIZE_1BPP EQU 8 ; bytes
DEF tiles_1bpp EQUS "* TILE_SIZE_1BPP"

; icon tile offsets
DEF ICON_TILE_BASIC_POKEMON   EQU $b0
DEF ICON_TILE_STAGE_1_POKEMON EQU $b4
DEF ICON_TILE_STAGE_2_POKEMON EQU $b8
DEF ICON_TILE_TRAINER         EQU $bc

DEF ICON_TILE_FIRE            EQU $c0
DEF ICON_TILE_GRASS           EQU $c4
DEF ICON_TILE_LIGHTNING       EQU $c8
DEF ICON_TILE_WATER           EQU $cc
DEF ICON_TILE_FIGHTING        EQU $d0
DEF ICON_TILE_PSYCHIC         EQU $d4
DEF ICON_TILE_DARKNESS        EQU $d8
DEF ICON_TILE_COLORLESS       EQU $dc
DEF ICON_TILE_ENERGY          EQU $e0

; graphics table constants
; (see src/engine/gfx/gfx_table_pointers.asm)
RSRESET
DEF GFXTABLE_TILEMAPS          RW ; $0
DEF GFXTABLE_TILESETS          RW ; $2
DEF GFXTABLE_SPRITES           RW ; $4
DEF GFXTABLE_SPRITE_ANIMATIONS RW ; $6
DEF GFXTABLE_PALETTES          RW ; $8
DEF GFXTABLE_PORTRAITS         RW ; $a
